version: "3.8"
services:
  app:
    image: ghcr.io/remla23-team08/app:latest
    ports:
      - "8083:8083"
    environment:
      - MODEL_SERVICE_URL=http://model-service:8080

  model-service:
    image: ghcr.io/remla23-team08/model-service:latest
    ports:
      - "8080:8080"
      