apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
{{- with .Values.prometheus }}
metadata:
  name: {{ .name }}-entry-service
spec:
  gateways:
    - {{ $.Release.Name }}-gateway
  hosts:
    - {{ .host }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ $.Values.prometheus.release }}-kube-prometheus-prometheus
            port:
              number: {{ .port }}
{{- end }}