{{ $prometheusPort := .Values.prometheus.port }}
{{- with .Values.app }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-deployment-v1
  labels: {app: {{ .name }}, version: v1}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels: {app: {{ .name }}, version: v1}
  template:
    metadata:
      labels: {app: {{ .name }}, version: v1}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ $prometheusPort }}"
    spec:
      containers:
      - name: {{ .name }}
        imagePullPolicy: Always
        image: ghcr.io/remla23-team08/app:{{ .image.version1 }}
        ports:
        - containerPort: {{ .port }}
        env:
        - name: MODEL_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ .name }}-configmap
              key: model-service-url
{{- end }}
        