{{- with .Values.app }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-svc
  labels:
    app: {{ .name }}-svc
spec:
  type: {{ .service.type }}
  selector:
    app: {{ .name }}
  ports:
    - name: http-{{ .name }}-port
      port: {{ .port }}
      targetPort: {{ .port }}
{{- end }}
