{{- with .Values.modelService }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-deployment
  labels:
    app: {{ .name }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      - name: {{ .name }}
        image: ghcr.io/remla23-team08/model-service:{{ .version }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .port }}
{{- end }}
