apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
{{- with .Values.modelService }}
metadata:
  name: {{ .name }}-destination-rule
spec:
  host: {{ .name }}-svc
  subsets:
  - name: {{ .version1.name }}
    labels:
      version: {{ .version1.name }}
  - name: {{ .version2.name }}
    labels:
      version: {{ .version2.name }}
{{- end }}