apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
{{- with .Values.modelService }}
metadata:
  name: {{ .name }}-destination-rule
spec:
  host: {{ .name }}-svc
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
{{- end }}