{{- with .Values.modelService }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .name }}-monitor
  labels:
    app: {{ .name }}-svc
    release: {{ $.Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .name }}-svc
  endpoints:
    - interval: {{ .monitoring.endpointsIntervalSeconds}}s
    # path: /metrics
{{- end }}
