apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
{{- with .Values.modelService }}
metadata:
  name: {{ .name }}-entry-service
spec:
  gateways:
    - {{ $.Release.Name }}-gateway
  hosts:
    - {{ .host }}
  http:
    - match:
        - uri:
            prefix: /
          headers:
            cookie:
              regex: ".*{{ .name }}-version={{ .version1.name }}.*"
      route:
        - destination:
            host: {{ .name }}-svc
            subset: {{ .version1.name }}
            port:
              number: {{ .port }}
    - match:
        - uri:
            prefix: /
          headers:
            cookie:
              regex: ".*{{ .name }}-version={{ .version2.name }}.*"
      route:
        - destination:
            host: {{ .name }}-svc
            subset: {{ .version2.name }}
            port:
              number: {{ .port }}
    - route:
        - destination:
            host: {{ .name }}-svc
            subset: {{ .version1.name }}
            port:
              number: {{ .port }}
          weight: {{ .version1.weight }}
          headers:
            response:
              set:
                Set-Cookie: "{{ .name }}-version={{ .version1.name }}"
        - destination:
            host: {{ .name }}-svc
            subset: {{ .version2.name }}
            port:
              number: {{ .port }}
          weight: {{ .version2.weight }}
          headers:
            response:
              set:
                Set-Cookie: "{{ .name }}-version={{ .version2.name }}"
{{- end }}