{{- with .Values.modelService }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-deployment-{{ .version1.name }}
  labels:
    app: {{ .name }}
    version: {{ .version1.name }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
      version: {{ .version1.name }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .port }}"
      labels:
        app: {{ .name }}
        version: {{ .version1.name }}
    spec:
      containers:
      - name: {{ .name }}
        image: ghcr.io/remla23-team08/model-service:{{ .version1.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .port }}
        volumeMounts:
          - name: model-volume-{{ .version1.name }}
            mountPath: /root/ml-model
      volumes:
        - name: model-volume-{{ .version1.name }}
          hostPath:
            path: ml-model-canary
{{- end }}
