{
 "title": "Restaurant Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Stable Release Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of reviews",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(predictions_created{version=\"stable\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Reviews and predictions over time",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 20, "x": 4, "y": 1 },
     "targets": [
      {
       "expr": "sum(predictions_total{version=\"stable\"})",
       "legendFormat": "Total Predictions"
      },
      {
       "expr": "sum(pos_predictions_total{version=\"stable\"})",
       "legendFormat": "Positive Predictions"
      },
      {
       "expr": "sum(neg_predictions_total{version=\"stable\"})",
       "legendFormat": "Negative Predictions"
      }
     ]
    },
    {
     "title": "Average Model Accuracy",
     "type": "gauge",
     "description": "Average over the timeframe/interval selected by user",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(model_accuracy{version=\"stable\"})",
       "legendFormat": "Model Accuracy"
      }
     ]
    },
    {
     "title": "Number of positive predictions",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pos_predictions_total{version=\"stable\"})",
       "legendFormat": "Positive predictions"
      },
      {
       "expr": "sum(true_pos_predictions_total{version=\"stable\"})",
       "legendFormat": "True positive predictions"
      },
      {
       "expr": "sum(false_pos_predictions_total{version=\"stable\"})",
       "legendFormat": "False positive predictions"
      }
     ]
    },
    {
     "title": "Number of negative predictions",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(neg_predictions_total{version=\"stable\"})",
       "legendFormat": "Negative predictions"
      },
      {
       "expr": "sum(true_neg_predictions_total{version=\"stable\"})",
       "legendFormat": "True negative predictions"
      },
      {
       "expr": "sum(false_neg_predictions_total{version=\"stable\"})",
       "legendFormat": "False negative predictions"
      }
     ]
    }
   ]
  },
  { "title": "Canary Release Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total number of reviews",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(predictions_total{version=\"canary\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reviews and predictions over time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 20, "x": 4, "y": 2 },
   "targets": [
    {
     "expr": "sum(predictions_total{version=\"canary\"})",
     "legendFormat": "Total Predictions"
    },
    {
     "expr": "sum(pos_predictions_total{version=\"canary\"})",
     "legendFormat": "Positive Predictions"
    },
    {
     "expr": "sum(neg_predictions_total{version=\"canary\"})",
     "legendFormat": "Negative Predictions"
    }
   ]
  },
  {
   "title": "Average Model Accuracy",
   "type": "gauge",
   "description": "Average over the timeframe/interval selected by user",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(model_accuracy{version=\"canary\"})",
     "legendFormat": "Model Accuracy"
    }
   ]
  },
  {
   "title": "Number of positive predictions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pos_predictions_total{version=\"canary\"})",
     "legendFormat": "Positive predictions"
    },
    {
     "expr": "sum(true_pos_predictions_total{version=\"canary\"})",
     "legendFormat": "True positive predictions"
    },
    {
     "expr": "sum(false_pos_predictions_total{version=\"canary\"})",
     "legendFormat": "False positive predictions"
    }
   ]
  },
  {
   "title": "Number of negative predictions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(neg_predictions_total{version=\"canary\"})",
     "legendFormat": "Negative predictions"
    },
    {
     "expr": "sum(true_neg_predictions_total{version=\"canary\"})",
     "legendFormat": "True negative predictions"
    },
    {
     "expr": "sum(false_neg_predictions_total{version=\"canary\"})",
     "legendFormat": "False negative predictions"
    }
   ]
  },
  { "title": "Restaurant Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Total number of reviews per restaurant",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(restaurant_name) (predictions_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reviews over time per restaurant",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 23 },
   "targets": [
    {
     "expr": "sum by(restaurant_name) (predictions_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Positive predictions per restaurant",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(restaurant_name) (pos_predictions_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Negative predictions per restaurant",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(restaurant_name) (neg_predictions_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}