{
 "title": "Metrics Visualisation",
 "time": { "from": "2023-05-17T16:56:44.000Z", "to": "2023-05-17T16:58:28.000Z" },
 "panels": [
  {
   "title": "Total number of reviews",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "predictions_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of positive reviews",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "true_pos_predictions_total + false_neg_predictions_total",
     "legendFormat": "Number of positive reviews"
    },
    { "expr": "pos_predictions_total", "legendFormat": "Number of positive predictions" }
   ]
  },
  {
   "title": "Predictions over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "predictions_total", "legendFormat": "Total Predictions" },
    { "expr": "pos_predictions_total", "legendFormat": "Positive Predictions" },
    { "expr": "neg_predictions_total", "legendFormat": "Negative Predictions" }
   ]
  },
  {
   "title": "Number of negative reviews",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "true_neg_predictions_total + false_pos_predictions_total",
     "legendFormat": "Number of negative reviews"
    },
    {
     "expr": "neg_predictions_total",
     "legendFormat": "Predicted number of negative reviews"
    }
   ]
  },
  {
   "title": "Average Model Accuracy (over selected timeframe)",
   "type": "gauge",
   "description": "Average over the timeframe/interval selected by user",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance) (model_accuracy)",
     "legendFormat": "Model Accuracy"
    }
   ]
  }
 ]
}