# Values for k8s app-related templates
app:
  # This is the name of the application (used in labels, service names, etc.)
  name: app

  # This is the docker image tag to use for the application
  version: latest

  # This is the number of replicas to run for the application
  replicaCount: 1

  # This is the port that the application listens on
  port: 8083

  # This the host for the application
  host: app.localhost

  # For app-svc related properties
  service:
    # The type to use for the service (default is ClusterIP)
    type: ClusterIP

# Values for k8s model-service-related templates
modelService:
  # This is the name of the model service (used in labels, service names, etc.)
  name: model-service

  # These are the versions to use for the model service canary rollout
  version1:
    # Version name
    name: canary
    # Version image tag
    tag: 0.1.26-canary
    # Version traffic distribution
    weight: 30

  version2:
    # Version name
    name: stable
    # Version image tag
    tag: latest
    # Version traffic distribution
    weight: 70

  # This is the number of replicas to run for the model service
  replicaCount: 1

  # This is the port that the model service listens on
  port: 8080

  # This the host for the model service
  host: service.localhost

  # For model-service-svc related properties
  service:
    # The type to use for the service (default is ClusterIP)
    type: ClusterIP

  # For model-service-monitor related properties
  monitoring:
    # The interval to use for the service monitor (default is 10s)
    endpointsIntervalSeconds: 10

rateLimit:
  # Domain name used in rate limit
  domain: app-ratelimit
