app:
  name: app
  version: latest
  replicaCount: 1
  port: 8083
modelService:
  name: model-service
  version: latest
  replicaCount: 1
  predictRoute: predict
  port: 8080
  monitoring:
    endpointsIntervalSeconds: 10
