apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $.Release.Name }}-istio-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $.Release.Name }}-istio-virtualservice
spec:
  gateways:
    - {{ $.Release.Name }}-istio-gateway
  hosts:
    - "*"
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ .Values.app.name }}-svc
        subset: v1
      weight: 90
    - destination:
        host: {{ .Values.app.name }}-svc
        subset: v2
      weight: 10
---
{{- with .Values.modelService }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .name }}-istio-destination-rule
spec:
  host: {{ .name }}-svc
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
{{- end }}
---
{{- with .Values.app }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .name }}-istio-destination-rule
spec:
  host: {{ .name }}-svc
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
{{- end }}
