apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: model-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: model-service-svc
  endpoints:
    - interval: 1s
