name: Build Pipeline
on: [pull_request]

jobs:
  lint:
    name: helm-charts-lint-validation
    runs-on: ubuntu-22.04
    steps:
      - name: Generate GitHub App Token
        id: generate_github_app_token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_github_app_token.outputs.token }}
          persist-credentials: true
      
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: latest
          token: ${{ steps.generate_github_app_token.outputs.token }}
      
      - name: Chart Validation
        run: |
          helm lint ./charts/*/
      